### PR TITLE
Add "src" as image source

### PR DESCRIPTION
**Pull request by leoz**

### CODE REVIEW

**Comment by Luehang** [comment]
Hi,

Thanks for trying to contribute.  Before I can merge this pull request, can you try to fix it with the following, and tell me what you think?

Standard and well known declaration for remote and local images  in **React Native** is the prop `source={uri: ""}` or `source={require("yourApp/image.png")}`.  To improve this logic you are trying to add, I think you should compare `src` to see if it is an `object` data type with the field name `uri`.  After that, compare `src` to see if it is a `string` data type.

From,

Lue Hang

**Comment by leoz** [comment]
@Luehang , this makes sense.
Could you please point me out where you do this in your code for other non-standard image declarations like e.g. "URL"?

**Comment by Luehang** [comment]
Hi,

Those are fail safe field names.

> A URI can be further classified as a locator, a name, or both. The term “Uniform Resource Locator” (URL) refers to the subset of URIs that, in addition to identifying a resource, provide a means of locating the resource by describing its primary access mechanism (e.g., its network “location”).

I only ask to check if the `src` field name has an object in it first and then checks for a string.

Thanks for trying to contribute.

**Comment by leoz** [comment]
@Luehang , I was just curious to find out what makes them "fail safe"?
They all come from external JSON which potentially could have any type mismatch.
The policy shall apply to any input the same way: you whether trust all input types or you do not.

**Comment by Luehang** [comment]
Either you try to improve the logic or stop complaining.

**Pull request closed without merging**
